server:
  port: 8091

opentracing:
  jaeger:
    service-name: DemoOpentracingTest123
    enable: true
    udp-sender:
      host: 192.160.0.114

spring:
  sleuth:
    sampler:
      percentage: 0.1
    web:
      skipPattern: (^cleanup.*|.+favicon.*)
  zipkin:
    base-url: http://localhost:9411/

  datasource:
    url: jdbc:mysql://localhost:3306/insurance_web_application
    username: root
    password: 4564
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: user-Management-Microservice

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
  file:
    name: insurance_web_application.log