server:
  port: 8095

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
  file:
    name: insurance_web_application.log

spring:
  cloud:
    gateway:
      routes:
        - id: USER-MANAGEMENT-SERVICE
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/users/**
        - id: POLICY-MANAGEMENT-SERVICE
          uri: lb://POLICY-MANAGEMENT-SERVICE
          predicates:
            - Path=/policy/**
        - id: CLAIMS-MANAGEMENT-SERVICE
          uri: lb://CLAIMS-MANAGEMENT-SERVICE
          predicates:
            - Path=/claims/**
        - id: BILLING-MANAGEMENT-SERVICE
          uri: lb://BILLING-MANAGEMENT-SERVICE
          predicates:
            - Path=/bills/**
  application:
    name: API-GATEWAY-MICROSERVICE