server:
  port: 8093

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insurance_web_application
    username: root
    password: 4564
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
  file:
    name: insurance_web_application.log